# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/procEC/Lab5_EC/Lab5_EC.cache/wt [current_project]
set_property parent.project_path C:/procEC/Lab5_EC/Lab5_EC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/new/mux4a1_4bits.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion1/hex2led.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion1/dec2a4.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion4/unicontrol_rel1.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion2/registro_PC.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion3/ram_datos.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion4/mux3a1_5bits.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion4/mux3a1_16bits.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion4/mux2a1_16bits.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion3/Mem_Ia_256x8.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion4/BReg_3port_lec.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion4/ALUcontrol_0.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/new/ALU16bits.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion1/Sel_Digit_CodLEDS.vhd
  C:/procEC/Lab5_EC/Lab5_EC.srcs/sources_1/imports/Sesion5/cont_pausa_gen.vhd
  C:/procEC/Lab5_EC/Lab5_EC.srcs/sources_1/imports/Sesion5/cont_div_frec_refresh.vhd
  C:/procEC/Lab4_EC/Lab1_EC.srcs/sources_1/imports/Sesion4/Mips_Nucleo1.vhd
  C:/procEC/Lab5_EC/Lab5_EC.srcs/sources_1/imports/Sesion5/MIPS_interface.vhd
}
read_xdc C:/procEC/Lab5_EC/Lab5_EC.srcs/constrs_1/imports/Sesion5/nexys4ddr.xdc
set_property used_in_implementation false [get_files C:/procEC/Lab5_EC/Lab5_EC.srcs/constrs_1/imports/Sesion5/nexys4ddr.xdc]

synth_design -top MIPS_interface -part xc7a100tcsg324-1
write_checkpoint -noxdef MIPS_interface.dcp
catch { report_utilization -file MIPS_interface_utilization_synth.rpt -pb MIPS_interface_utilization_synth.pb }
