# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/procEC/Lab1_EC/Lab1_EC.cache/wt [current_project]
set_property parent.project_path C:/procEC/Lab1_EC/Lab1_EC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/procEC/Lab1_EC/Lab1_EC.srcs/sources_1/new/ALU16bits.vhd
synth_design -top ALU16bits -part xc7a100tcsg324-1
write_checkpoint -noxdef ALU16bits.dcp
catch { report_utilization -file ALU16bits_utilization_synth.rpt -pb ALU16bits_utilization_synth.pb }
